# Generated by Django 5.2.2 on 2025-06-15 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("EXCEPTION", "Exception"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("logger_name", models.CharField(db_index=True, max_length=100)),
                ("module", models.CharField(blank=True, max_length=100)),
                ("function_name", models.CharField(blank=True, max_length=100)),
                ("line_number", models.PositiveIntegerField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=36)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, db_index=True, max_length=500)),
                ("response_time_ms", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("status_code", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("app_name", models.CharField(db_index=True, default="skillforge", max_length=50)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("testing", "Testing"),
                        ],
                        db_index=True,
                        default="development",
                        max_length=20,
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("exception_info", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
