# Generated by Django 5.2.2 on 2025-07-13 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["level", "-timestamp"], name="log_logentr_level_c58bd9_idx"),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["logger_name", "-timestamp"], name="log_logentr_logger__9d6ead_idx"),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["user", "-timestamp"], name="log_logentr_user_id_caa998_idx"),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["app_name", "level", "-timestamp"], name="log_logentr_app_nam_77d27c_idx"),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["request_path", "-timestamp"], name="log_logentr_request_37d8e2_idx"),
        ),
        migrations.AddIndex(
            model_name="logentry",
            index=models.Index(fields=["status_code", "-timestamp"], name="log_logentr_status__a6cab9_idx"),
        ),
    ]
