volumes:
  postgres_data: {}

services:
  web:
    container_name: web-1
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    image: skillforge
    stdin_open: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - qcluster
    env_file:
      - ./dev.env
    restart: unless-stopped

  db:
    restart: always
    container_name: db-1
    image: postgres:16.2-bullseye
    env_file:
      - ./dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "skillforge-dev"
      POSTGRES_USER: "skillforge"
      POSTGRES_PASSWORD: "skillforge"
  redis:
    container_name: redis-1
    image: redis:alpine
    env_file:
      - ./dev.env
    ports:
      - "6379:6379"
    hostname: redis
    restart: unless-stopped

  qcluster:
    container_name: qcluster-1
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py qcluster
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - ./dev.env
    restart: on-failure