# Generated by Django 5.2.2 on 2025-06-29 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionServiceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Category Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
            ],
            options={
                "verbose_name": "Subscription Service Category",
                "verbose_name_plural": "Subscription Service Categories",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Subscription Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                ("website_url", models.URLField(blank=True, verbose_name="Website URL")),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Amount"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Turkish Lira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CNY", "Chinese Yuan"),
                            ("RUB", "Russian Ruble"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="TRY",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50, verbose_name="Payment Method")),
                ("free_trial_days", models.PositiveIntegerField(blank=True, null=True)),
                ("free_trial_available", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False, verbose_name="Is Active")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_services",
                        to="finance.subscriptionservicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Service",
                "verbose_name_plural": "Subscription Services",
            },
        ),
    ]
