# Generated by Django 5.2.2 on 2025-06-29 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("plan_name", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Turkish Lira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CNY", "Chinese Yuan"),
                            ("RUB", "Russian Ruble"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annually", "Semi-Annually"),
                            ("annually", "Annually"),
                        ],
                        default="monthly",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("started_at", models.DateField()),
                ("next_billing_date", models.DateField()),
                ("trial_end_date", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial Period"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending Activation"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_renewal", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("wire_transfer", "Wire Transfer"),
                            ("eft", "EFT"),
                            ("paypal", "PayPal"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("samsung_pay", "Samsung Pay"),
                            ("amazon_pay", "Amazon Pay"),
                            ("paycell", "Paycell"),
                            ("turkcell_paycell", "Turkcell Paycell"),
                            ("vodafone_cuzdan", "Vodafone Cüzdan"),
                            ("klarna", "Klarna"),
                            ("maxi", "Maxi"),
                            ("hopi", "Hopi"),
                            ("bitcoin", "Bitcoin"),
                            ("ethereum", "Ethereum"),
                            ("usdt", "USDT"),
                            ("binance_pay", "Binance Pay"),
                            ("crypto_other", "Other Cryptocurrency"),
                            ("stripe", "Stripe"),
                            ("square", "Square"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payment_account", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to="finance.subscriptionservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
            },
        ),
    ]
