# Generated by Django 4.2.7 on 2025-05-28 22:38

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("first_name", core.fields.NullableCharField(default=None, max_length=254)),
                ("middle_name", core.fields.NullableCharField(default=None, max_length=254)),
                ("last_name", core.fields.NullableCharField(default=None, max_length=254)),
                ("full_name", core.fields.NullableCharField(default=None, max_length=254)),
                ("nickname", core.fields.NullableCharField(default=None, max_length=254)),
                ("email", core.fields.NullableCharField(default=None, max_length=254)),
                ("emails", models.JSONField(blank=True, default=list)),
                ("phones", models.JSONField(blank=True, default=list)),
                ("mobile_phone", core.fields.NullableCharField(default=None, max_length=16)),
                ("home_phone", core.fields.NullableCharField(default=None, max_length=16)),
                ("work_phone", core.fields.NullableCharField(default=None, max_length=16)),
                ("second_phone", core.fields.NullableCharField(default=None, max_length=16)),
                ("third_phone", core.fields.NullableCharField(default=None, max_length=16)),
                ("addresses", models.JSONField(blank=True, default=list)),
                ("organization", core.fields.NullableCharField(default=None, max_length=254)),
                ("job_title", core.fields.NullableCharField(default=None, max_length=254)),
                ("department", core.fields.NullableCharField(default=None, max_length=254)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("anniversary", models.DateField(blank=True, null=True)),
                ("websites", models.JSONField(blank=True, default=list)),
                ("social_profiles", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "import_source",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("outlook", "Outlook"),
                            ("sim", "SIM Card"),
                            ("icloud", "iCloud"),
                            ("csv", "CSV File"),
                            ("manual", "Manuel Entry"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("samsung", "Samsung"),
                            ("vcard", "vCard"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("external_id", core.fields.NullableCharField(default=None, max_length=254)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("photo_url", models.URLField(blank=True, default="")),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
                "unique_together": {("owner", "external_id", "import_source")},
            },
        ),
        migrations.CreateModel(
            name="ContactBackup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("contact_data", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups",
                        to="contact.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
