# Generated by Django 5.2.2 on 2025-06-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["first_name", "middle_name", "last_name"]},
        ),
    ]
