# Generated by Django 5.2.2 on 2025-07-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo_file",
            field=models.FileField(
                blank=True, help_text="Optional photo file for the contact", null=True, upload_to="contact_photos/"
            ),
        ),
    ]
