# Generated by Django 5.2.2 on 2025-06-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactbackup",
            name="contact_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
