# Generated by Django 5.2.2 on 2025-07-12 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_contactbackup_contact_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="owner",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="contactbackup",
            old_name="owner",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("user", "external_id", "import_source")},
        ),
    ]
