# Generated by Django 5.2.2 on 2025-07-13 12:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_rename_owner_contact_user_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[
                ("contact_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
