# Generated by Django 5.2.2 on 2025-07-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0005_alter_contact_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[],
        ),
        migrations.AddField(
            model_name="contact",
            name="photo_base64",
            field=models.TextField(blank=True, default=""),
        ),
    ]
