# Generated by Django 5.2.2 on 2025-07-02 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntentPattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("intent_name", models.CharField(db_index=True, max_length=100)),
                ("keywords", models.JSONField(default=list, help_text="Keywords for this intent")),
                ("required_words", models.JSONField(default=list, help_text="Must-have words")),
                ("weight", models.FloatField(default=1.0, help_text="Pattern importance weight")),
                ("confidence_threshold", models.FloatField(default=0.3)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("accuracy_rate", models.FloatField(default=0.0)),
                ("auto_generated", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["intent_name"], name="ai_intentpa_intent__32c641_idx"),
                    models.Index(fields=["accuracy_rate"], name="ai_intentpa_accurac_c5b0cd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("telegram_user_id", models.BigIntegerField(db_index=True)),
                ("message_text", models.TextField()),
                ("processed_text", models.TextField()),
                ("detected_intent", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("extracted_entities", models.JSONField(default=dict)),
                ("user_confirmed", models.BooleanField(blank=True, null=True)),
                ("correct_intent", models.CharField(blank=True, max_length=100, null=True)),
                ("feedback_received", models.BooleanField(default=False)),
                (
                    "pattern_used",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ai.intentpattern"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("correct", "Correct Response"),
                            ("wrong_intent", "Wrong Intent Detected"),
                            ("missing_info", "Missing Information"),
                            ("unclear", "Unclear Response"),
                        ],
                        max_length=50,
                    ),
                ),
                ("suggested_intent", models.CharField(blank=True, max_length=100, null=True)),
                ("feedback_text", models.TextField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                ("applied_to_model", models.BooleanField(default=False)),
                ("user_message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ai.usermessage")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LearnedKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(db_index=True, max_length=100)),
                ("intent", models.CharField(db_index=True, max_length=100)),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("confidence", models.FloatField(default=0.5)),
                ("auto_discovered", models.BooleanField(default=True)),
                (
                    "learned_from_message",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="ai.usermessage"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="usermessage",
            index=models.Index(fields=["telegram_user_id"], name="ai_usermess_telegra_f0f529_idx"),
        ),
        migrations.AddIndex(
            model_name="usermessage",
            index=models.Index(fields=["detected_intent"], name="ai_usermess_detecte_523137_idx"),
        ),
        migrations.AddIndex(
            model_name="learnedkeyword",
            index=models.Index(fields=["intent", "confidence"], name="ai_learnedk_intent_16b87a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="learnedkeyword",
            unique_together={("keyword", "intent")},
        ),
    ]
