# Generated by Django 5.2.2 on 2025-06-29 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0002_usersubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("snoozed", "Snoozed"),
                        ],
                        default="pending",
                        max_length=35,
                    ),
                ),
                ("reminder_date", models.DateTimeField(verbose_name="Reminder Date Time")),
                ("scheduled_at", models.DateTimeField(blank=True, null=True, verbose_name="Scheduled At")),
                ("is_notified", models.BooleanField(default=False, verbose_name="Is Notified")),
                ("is_recurring", models.BooleanField(default=False, verbose_name="Is Recurring")),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("snooze_count", models.PositiveIntegerField(default=0)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Turkish Lira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CNY", "Chinese Yuan"),
                            ("RUB", "Russian Ruble"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="TRY",
                        max_length=3,
                    ),
                ),
                (
                    "finance_category",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("business", "Business"),
                            ("investment", "Investment"),
                            ("loan", "Loan"),
                            ("credit_card", "Credit Card"),
                            ("mortgage", "Mortgage"),
                            ("other", "Other"),
                            ("entertainment", "Entertainment"),
                            ("subscription", "Subscription"),
                            ("travel", "Travel"),
                            ("utilities", "Utilities"),
                            ("transportation", "Transportation"),
                            ("food", "Food & Dining"),
                            ("shopping", "Shopping"),
                            ("health", "Health & Medical"),
                            ("education", "Education"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("wire_transfer", "Wire Transfer"),
                            ("eft", "EFT"),
                            ("paypal", "PayPal"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("samsung_pay", "Samsung Pay"),
                            ("amazon_pay", "Amazon Pay"),
                            ("paycell", "Paycell"),
                            ("turkcell_paycell", "Turkcell Paycell"),
                            ("vodafone_cuzdan", "Vodafone Cüzdan"),
                            ("klarna", "Klarna"),
                            ("maxi", "Maxi"),
                            ("hopi", "Hopi"),
                            ("bitcoin", "Bitcoin"),
                            ("ethereum", "Ethereum"),
                            ("usdt", "USDT"),
                            ("binance_pay", "Binance Pay"),
                            ("crypto_other", "Other Cryptocurrency"),
                            ("stripe", "Stripe"),
                            ("square", "Square"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("autopay_enabled", models.BooleanField(default=False)),
                ("send_sms_reminder", models.BooleanField(default=True)),
                ("send_email_reminder", models.BooleanField(default=True)),
                ("alert_days_before", models.PositiveIntegerField(default=3)),
                ("late_fee_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_reminders",
                        to="finance.subscriptionservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Reminder",
                "verbose_name_plural": "Finance Reminders",
            },
        ),
    ]
